### PR TITLE
 Cursor as Pointer on hover in NavBar also Added Close button on the login/signup pop up

### PR DESCRIPTION
**Pull request by sau-mili**
I made the change according to issue  [#6 ](url) @piug-07 please check

### CODE REVIEW

**Comment by sau-mili** [comment]
Can you please check this? @piug-07 I made an issue for this as well [#6 ](url)

**Comment by sau-mili** [comment]
can you please check this?

**Comment by sau-mili** [comment]
@piug-07 Please check this pull Request

**Comment by sau-mili** [comment]
resolves #6

**Comment by mfatima05** [comment]
I have merged your PR

**Pull request merged**
