### PR TITLE
feat: Enhancement of home page

### PR DESCRIPTION
**Pull request by AshmitaBarthwal**
## Related Issue
Issue no. : #695
Title: Enhancement Of Home Page

## Description
Modified the home page to make it attractive to the users.
Created a glass body for the text with a blended background according to the theme of the webpage.

## Type of PR

- [ ] Bug fix
- [X] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)
MODIFIED HOME PAGE:

Screenshot 2024-07-23 110600

Screenshot 2024-07-23 110612

## Checklist:
- [X] I have performed a self-review of my code.
- [X] I have read and followed the Contribution Guidelines outlined in the project's documentation.
- [X] I have thoroughly tested the changes before submitting this pull request.
- [X] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [X] I have commented my code, particularly in hard-to-understand areas.

## Additional Context:
I AM A CONTRIBUTING MEMBER OF GSSOC 24.

### CODE REVIEW

**Comment by AshmitaBarthwal** [comment]
@piyushg-07 Please review my PR.

**Comment by AshmitaBarthwal** [comment]
@piyushg-07 please add LABELS - GSSOC and LEVEL OF CONTRIBUTION to my PR so that it can be considered.

**Comment by AshmitaBarthwal** [comment]
@piyushg-07 Please review my PR.

**Comment by AshmitaBarthwal** [comment]
@MastanSayyad could you help in this, as my PR is not being reviewed.

**Comment by MastanSayyad** [comment]
This is a flagged repository, it is not counting under gssoc anymore! @AshmitaBarthwal

**Pull request closed without merging**
