### PR TITLE
login page

### PR DESCRIPTION
**Pull request by Its-your-rj**
## Related Issue
- #478

## Description
I have created a login page in this website which cover some basic functionalities and has also provided appropriate style to it.

## Type of PR
- Made a Login Page
- provided appropriate styling to it
- Made the UI more user friendly
## Screenshots 
Screenshot 2024-06-10 124824

## Checklist:
- [x] I have performed a self-review of my code.
- [x] I have read and followed the Contribution Guidelines outlined in the project's documentation.
- [x] I have thoroughly tested the changes before submitting this pull request.
- [x] I have provided relevant issue numbers, screenshots after making the changes.
- [x] I have commented my code, particularly in hard-to-understand areas.

## Additional Context:
Please add Labels to it and merge it under GSSOC'24 and level 3 label

### CODE REVIEW

**Comment by Its-your-rj** [comment]
@piug-07 please merge it along with the label of level3 and GSSOC it would be a great help to me.
Thanking you 
Raj Mehta

**Comment by Its-your-rj** [comment]
@piug-07 please merege it and close the pull request

**Comment by sanjay-kv** [comment]
@piug-07 i reached out you to many times regarding the labels you following on the repo is wrong. it should be `gssoc` , `level3`

+ I have requested you to add me into the repo to fix label issues.

**Comment by Its-your-rj** [comment]
@piug-07 please update the labels to gssoc and level3 like this. It would be a great help to me.

**Pull request merged**
