### PR TITLE
Added video ready to watch according to video description from youtube and enhanced UI of blog post

### PR DESCRIPTION
**Pull request by Richasawatkar**
Here's how it looks now: 

https://github.com/piug-07/blogzen-OpenSource/assets/127492462/9e24e9a1-a777-42d7-a2d4-a2cf241bea29

I have added youtube videos corresponding to each topic.I  have also added background color to navbar and changed color fonts. Decreased the size of the text.

### CODE REVIEW

**Comment by Richasawatkar** [comment]
Please consider this for gssoc submission

**Comment by piug-07** [comment]
there is conflict in file pull all the changes and create again a pull req.

**Comment by Richasawatkar** [comment]
Ok

**Comment by Richasawatkar** [comment]
Do I need to close this pull request and create another new one?

**Comment by mfatima05** [comment]
@Richasawatkar did you create an issue for this?

**Comment by mfatima05** [comment]
I will not be able to merge it as the PR has conflict in it. Resolve this issue and recreate the PR as I am closing this one.

**Pull request closed without merging**
