### PR TITLE
Added responsivness to the website

### PR DESCRIPTION
**Pull request by Prince-kushwaha-2004**
## **Issue**: #60 Improving Overall Responsiveness of Website for Cross-Device Compatibility

I added **responsiveness** to website using flexbox property of CSS and media queries.

Screenshots are attached **Kindly check** and mention if any changes required.

Screenshot 2024-05-15 204233
Screenshot 2024-05-15 204212  Screenshot 2024-05-15 204203

### CODE REVIEW

**Comment by Prince-kushwaha-2004** [comment]
Kindly review this PR

**Comment by piug-07** [comment]
Search bar and blogzen header is not centered align the things and create again PR

**Comment by Prince-kushwaha-2004** [comment]
@piug-07 
I had fixed the aligment of Search bar and header.
Kindly review,


Screenshot 2024-05-27 095219
Screenshot 2024-05-27 095241

**Comment by mfatima05** [comment]
I will not be able to merge it as the PR has conflict in it. Resolve this issue and recreate the PR as I am closing this one.

**Pull request closed without merging**
