### PR TITLE
responsiveness added to the website

### PR DESCRIPTION
**Pull request by K-kiran77**
previously website is not responsive i have made the website responsive by changing some styles

website proviously when switched to small screen

https://github.com/piug-07/blogzen-OpenSource/assets/132844726/a9ddedfa-bc87-44ac-a01d-e318a799c744

website now when switched to small screen

https://github.com/piug-07/blogzen-OpenSource/assets/132844726/7da03a54-f03f-4ba0-b830-4f85c5b440c7

My issue no is #69

### CODE REVIEW

**Comment by piug-07** [comment]
modify and make the page proper responsive then create a PR

**Review by K-kiran77 — COMMENTED** [review]
I have made the nav bar more responsive compared to the previous commit and some minor changes have been done to make the website more responsive

**Comment by piug-07** [comment]
It's Look to bad to merge , review the design the make the changes

**Comment by K-kiran77** [comment]
If you don't mind could you please tell me which part of the website eg:-navbar, footer made you to feel bad in responsive

**Comment by mfatima05** [comment]
I will not be able to merge it as the PR has conflict in it. Resolve this issue and recreate the PR as I am closing this one.

**Pull request closed without merging**
