### PR TITLE
signUp is working

### PR DESCRIPTION
**Pull request by bhavanishanker-png**
i build frontend of signUp page i will rise a issue for backend

### CODE REVIEW

**Comment by bhavanishanker-png** [comment]
i build frontend of signUp page i will rise a issue for backend

**Comment by bhavanishanker-png** [comment]
i build frontend of signUp page i will rise a issue for backend

**Comment by piug-07** [comment]
resolve your conflict and create a pull request again

**Comment by mfatima05** [comment]
resolve your conflict and create a pull request again

**Pull request closed without merging**
