### PR TITLE
Made the social media links working 

### LINKED ISSUE #625: FEATURE:Making social media links active
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### What feature would you like to see?

Previously when we press on any social media we are redirecting to page only again Now i will add the links for the social media links

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'24 contributor
- [X] I want to work on this feature

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
## Related Issue
Made the social media links working

## Description
made the social media links working

closes #625 

## Type of PR

- [ x] Bug fix
- [ ] Feature enhancement
- [ ] Documentation update
- [ ] Other (specify): _______________

## Screenshots / Videos (if applicable)
[Attach any relevant screenshots or videos demonstrating the changes made, if applicable.]

## Checklist:
- [ x] I have performed a self-review of my code.
- [ x] I have read and followed the Contribution Guidelines outlined in the project's documentation.
- [x ] I have thoroughly tested the changes before submitting this pull request.
- [x ] I have provided relevant issue numbers, screenshots, and videos after making the changes.
- [x ] I have commented my code, particularly in hard-to-understand areas.

## Additional Context:
[Include any additional information or context that might be helpful for reviewers. This could include details about any design decisions, potential impacts, or alternative approaches considered.]

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@piug-07 Please Review this Pull Request  soon

**Comment by Saipradyumnagoud** [comment]
@piyushg-07 Please Review the pull Request soon

**Comment by Saipradyumnagoud** [comment]
@sanjaykv could you please help me with the PR

**Comment by sanjay-kv** [comment]
I will share you a google form link later, so you can enter this pR.

**Comment by Saipradyumnagoud** [comment]
> I will share you a google form link later, so you can enter this pR. 

yes okay

**Comment by sanjay-kv** [comment]
I have no right to merge on other repo, I can only manage the labels. I will request admin to take action asap.

**Comment by Saipradyumnagoud** [comment]
> I have no right to merge on other repo, I can only manage the labels. I will request admin to take action asap. 

yes sir 
thank you @sanjay-kv

**Comment by Saipradyumnagoud** [comment]
@sanjay-kv  @piyushg-07 Because of No Review The PR Has been Closed

**Pull request closed without merging**
