### PR TITLE
Bug Fixes for Search Bar Functionality and Chatbot Response Issue

### PR DESCRIPTION
**Pull request by thevijayshankersharma**
This pull request addresses two critical issues affecting the functionality and user experience of the project. The first issue relates to the malfunctioning search bar feature, which fails to provide users with relevant search results. The second issue concerns the chatbot's inconsistent responses, where it repeatedly returns an error message regardless of user input. These issues significantly impact the usability and effectiveness of the application.

Issue #38 

Changes Proposed:

Search Bar Functionality Issue:

Implemented fixes to resolve the malfunctioning search feature.
Reviewed and adjusted search algorithms to ensure accurate and relevant search results.
Tested the search functionality across different scenarios to verify improvements.
Chatbot Response Issue:

Investigated potential causes for the chatbot's error-prone responses.
Identified and rectified errors in the API request handling and response processing.
Implemented error handling mechanisms to provide meaningful responses to users.
Conducted thorough testing to confirm the chatbot's ability to deliver relevant responses based on user input.

https://github.com/piug-07/blogzen-OpenSource/assets/109781385/8dc92c5b-4d93-4abd-ad71-e0a6e5ee8c5b

### CODE REVIEW

**Comment by thevijayshankersharma** [comment]
@mfatima05 Have a look.

**Comment by thevijayshankersharma** [comment]
@piug-07 Hey take a look here too.

**Comment by priyanshukumar397** [comment]
@piug-07 @mfatima05 - kindly take a look and resolve this and merge it!! 

Thanks - also @thevijayshankersharma resolve the conflicts in the branch and submit once again if possible!!

**Comment by thevijayshankersharma** [comment]
> @piug-07 @mfatima05 - kindly take a look and resolve this and merge it!!
> 
> Thanks - also @thevijayshankersharma resolve the conflicts in the branch and submit once again if possible!!

Issues resolved.

**Comment by thevijayshankersharma** [comment]
@piug-07 Hey why did you close this PR without merging it ??

**Pull request closed without merging**
